# Generated by Django 2.2.6 on 2022-06-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20, null=True)),
                ('cSex', models.CharField(max_length=2, null=True)),
                ('cStudent_id', models.CharField(max_length=10, null=True)),
                ('cPassword', models.CharField(max_length=10, null=True)),
                ('cBirthday', models.DateField(null=True)),
                ('cEmail', models.EmailField(default='gmail', max_length=100, null=True)),
                ('cPhone', models.CharField(default='09', max_length=60, null=True)),
                ('cAddr', models.CharField(default='htt', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=100, null=True)),
                ('cPrice', models.IntegerField(null=True)),
                ('cUrl', models.CharField(max_length=100, null=True)),
                ('pName_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='catalog.Pname')),
            ],
        ),
    ]
