# Generated by Django 2.2.6 on 2022-06-04 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='select_v',
            field=models.CharField(choices=[(1, 'gtx1050'), (2, 'gtx1060')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
