# Generated by Django 2.2.6 on 2022-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_price_select_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='select_v',
            field=models.CharField(choices=[(-1, '全部顯示'), (1, 'gtx1050'), (2, 'gtx1060'), (3, 'gtx1070'), (4, 'gtx1080')], max_length=10),
        ),
    ]
