# Generated by Django 2.2.6 on 2022-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220604_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='web_record',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='select_v',
            field=models.CharField(choices=[(-1, '全部顯示'), (1, 'gtx1050'), (2, 'gtx1060'), (3, 'gtx1070'), (4, 'gtx1080')], max_length=10, null=True),
        ),
    ]
