# Generated by Django 4.1.3 on 2022-11-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_shoppingcart_useroeder_delete_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storeName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
