# Generated by Django 4.1.3 on 2022-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_storename'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImg',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
