# Generated by Django 4.1.3 on 2022-12-04 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_product_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_productBuy', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_userBuy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useroeder',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_productBuy', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='useroeder',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_userBuy', to=settings.AUTH_USER_MODEL),
        ),
    ]
