# Generated by Django 4.1.3 on 2022-12-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_shoppingcart_productid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=100)),
                ('orderAddr', models.CharField(max_length=100)),
                ('orderBuy', models.CharField(max_length=100)),
                ('orderPhone', models.CharField(max_length=12)),
                ('orderFee', models.IntegerField(default=10)),
                ('orderExtra', models.CharField(max_length=200)),
                ('orderStatus', models.IntegerField(choices=[(1, '待付款'), (2, '待發貨'), (3, '待收貨'), (4, '已完成')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productNum',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
