# Generated by Django 4.1.3 on 2022-12-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_orderinfo_product_productnum_product_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_num', models.IntegerField()),
                ('productInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderToProduct', to='catalog.product')),
                ('productOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderToInfo', to='catalog.orderinfo')),
            ],
        ),
    ]
